### ISSUE TITLE
dosen't seem to be compatible with trojan database requirement?

### ISSUE THREAD

**Issue by myfingerhurt** [llc1123/ssmgr-trojan-client#148]
version: 1.3.2
databse: mysql
Trojan: trojan-gfw/trojan
ssmgr: 0.36.68

```
CREATE TABLE users (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    username VARCHAR(64) NOT NULL,
    password CHAR(56) NOT NULL,
    quota BIGINT NOT NULL DEFAULT 0,
    download BIGINT UNSIGNED NOT NULL DEFAULT 0,
    upload BIGINT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    INDEX (password)
);
```

username  is the mandatory field, but instead, ssmgr-trojan-client is try to use the "port".

ssmgr-trojan-client log shown as below:
```
 [INFO] default - Message received: {"command":"add","port":60029,"password":"14f4ffe8604ab780b25bc729eb0c708f1b47f9dbbd4350c43aad8f7a"}
 [ERROR] default - Query error on 'add': ER_NO_DEFAULT_FOR_FIELD: Field 'username' doesn't have a default value
```
-----
version: 1.3.2
database: Redis
Trojan: trojan-gfw/trojan
ssmgr: 0.36.68

With the same configuration but Redis,  I get  "incorrect password", probably due to the same reason as the the mysql compliants about the "port" instead of "username", so the trojan can't read the correct password?  

Or maybe my misconfiguration?

Trojan log shown as below:
```
[ALL] 127.0.0.1:33912 incoming connection
[WARN] 127.0.0.1:33912 valid trojan request structure but possibly incorrect password (6c7f83d212bf6be15b78927895f9786c6c2d827979a7e57951b96114)
```

**Comment by llc1123** [comment]
mysql 中 username 字段没有任何用处，建表时可以不添加这个字段或者设置默认值（错误信息已经告诉你了）
redis 不需要提前建表，建议检查其他配置。
